### PR TITLE
KLC 3.0

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR brings the KLC rules in to line with the new naming scheme discussed [here](https://github.com/KiCad/kicad-library/issues/1622). Basically, all the rules have been renamed to match the new convention. The rule descriptions have also been updated slightly.

There are some other functional improvements:

**Rule scripts take their "name" from the filename**

Instead of having to having to both rename a file and also edit that file when moving rules around, each rule file takes its rule name from its filename. Just rename the file, and it will report a new rule name!

**Simplified rule names**
Rule names no longer have leading `rule` prefix.

This should be merged in unison with the new KLC going live on the [KiCad website](kicad-pcb.org).

The website branch I am working on is [here](https://github.com/schrodingersgat/kicad-website/tree/libraries)

Until then, review? Please pull this down and ensure that I haven't broken anything.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jkriege2 @poeschlr now that KLC3.0 is [up on the KiCad website](http://kicad-pcb.org/libraries/klc) then this needs to be merged.

Major changes:

* Rule naming has been changed to match new KLC rules
* A lot of small fixes to rule descriptions, etc
* Added some more checks
* Changed some errors to warnings to match `should` or `must` naming in KLC
* Fixes for rules that currently cause a lot of issues (e.g. custom pad layers for stencil aperture)

**Comment by poeschlr** [comment]
I played around with it a bit. (I have no real test lib.)
Seems to be ok. I think the real test will come when we check contributions with it.

So thanks for all the work you put into this.

**Comment by SchrodingersGat** [comment]
Thanks Rene

**Comment by poeschlr** [comment]
I fear there might be a problem thought:
I let it loose on one of the pull requests i handle and it seems to crash.
https://travis-ci.org/KiCad/Connectors_Molex.pretty/builds/295988843?utm_source=github_status&utm_medium=notification

**Comment by SchrodingersGat** [comment]
I'll look into that now

**Comment by SchrodingersGat** [comment]
Looks like a Python2 / Python3 thing. Gimme a sec

**Comment by poeschlr** [comment]
So we learned travis runs python3. Interesting.

**Comment by SchrodingersGat** [comment]
There will be some noise for a few minutes. It's doing some weird stuff that I can't replicate on my local machine

**Comment by SchrodingersGat** [comment]
Looks to be good now. Let's see how it goes on other PRs

**Comment by SchrodingersGat** [comment]
I have tested 10 other PRs and no further errors. Phew!

**Comment by poeschlr** [comment]
I like that https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/63 does no longer give a false positive.
And https://github.com/KiCad/Connectors.pretty/pull/88 still gives the same error messages (Well with the new numbers of course) so looks good as well.

**Comment by poeschlr** [comment]
Your pull request https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/68 still gives a KLC error. Even though your comment in that pull request indicated you would not expect an error with the new scripts. Have you been too optimistic or is there still a problem with travis?

**Comment by SchrodingersGat** [comment]
Not anymore it doesn't ;) The script performed as desired :)

**Pull request merged**
