### PR TITLE
.lib comparison

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds two key features:

**Component Checksum**
The schlib.py script now calculates component-level checksums. This can be used to determine which parts have been updated between different versions of the .lib file

**Library Comparison Script**
The *comparelibs.py* script takes two versions of a .lib file, and lists which components have been added / deleted / changed. If the --check flag is given, any updated/additional components are automagically run through the KLC script

(The -silent option for checklib.py has also been merged into this branch for argument pass-through)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Fixed conflicts

**Comment by SchrodingersGat** [comment]
I have now reduced the verbosity level of the KLC call, and added a return code for the comparison script.

**Comment by CarlPoirier** [comment]
This is awesome!

**Comment by jacobrosenthal** [comment]
Late thought on this. How about output being still color coded but with + - in front like a diff instead of the human readable. I think this is easier to parse by the next tool
```
-ACS712ELCTR-05B-T
-ACS711ELCTR-12AB
-ACS722LLCTR-05AB-T
-ACS754SCB-200
-ACS706ELC-05C
+ACS706ELC-WHATEVER1
+ACS706ELC-WHATEVER2
```

**Comment by jacobrosenthal** [comment]
Seems like youll want to probably do more of this in python yet, but Ill still keep problem solving in bash

Playing with this script https://github.com/jacobrosenthal/kicad-library/blob/master/test.sh to wget changed files and throw them at the new comparelibs.py

I posted here https://github.com/KiCad/kicad-library-utils/pull/48#issuecomment-243970675 but I think we could make comparelibs.py more parseable for the next step with + and - signs for components changed.

**Comment by jacobrosenthal** [comment]
Wrong window. Sorry for noise. Deleted that comment

**Comment by SchrodingersGat** [comment]
See https://github.com/KiCad/kicad-library-utils/pull/50 

Both suggestions have been implemented.

**Pull request merged**
