### PR TITLE
Footprint gen scripts (framework)

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR suggests a directory structure for adding current footprint and 3D-model generator scripts (which are currently floating around in various private repos) to the *official* utils repository.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jkriege2 e.g. instead of adding scripts to @pointhi repo they would be added here. Your extra tools would be welcome too.

Additionally it would be a good place to keep various FreeCAD scripts for parametric 3D model generation.

**Comment by jkriege2** [comment]
so do you want to fork https://github.com/pointhi/kicad-footprint-generator here?

**Comment by SchrodingersGat** [comment]
Essentially, yes. I have a whole bunch of scripts too, and have added a few extra features - https://github.com/SchrodingersGat/kicad-footprint-generator

**Comment by jkriege2** [comment]
Hhmmm ... then maybe we should ask @pointhi to merge all pending (and OK) PRs on his repo and the make a copy here?

JAN

**Comment by SchrodingersGat** [comment]
Ref https://github.com/pointhi/kicad-footprint-generator/issues/19

**Comment by SchrodingersGat** [comment]
@jkriege2 I have made a local copy of the KicadModTree tools and copied over most of my scripts (the 'better' ones, at least).

These scripts need to be updated to match the new KLC - I think that would be best done after they are merged here.

I would like to change all my scripts to make reference to global constants such as KLC_FAB_WIDTH - so that we can change just one value and fix all the scripts if we adjust KLC rules.

**Comment by pointhi** [comment]
@SchrodingersGat 
Things like line handling are already centralized in my script:
https://github.com/pointhi/kicad-footprint-generator/blob/master/KicadModTree/KicadFileHandler.py#L23

For scripting, I tried a new approach some time ago to separate footprint scripts and definitions: https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Shielding/wuerth_smd_shielding.kicad_mod.yaml
What do you think about it? I think this approach could improve footprint handling quite a bit (Also in connection with the footprint wizard / custom parts and the 3d-generation scripts)

There was already some initial planning, and the proposal has many similarities to the current footprint generator wizard: https://github.com/pointhi/kicad-footprint-generator/wiki/kicad_mod_generator

**Comment by jkriege2** [comment]
@SchrodingersGat I just saw that @pointhi merged my PRs on his FPGenerator repo ... maybe we can integrate that here?

see: 
  - https://github.com/pointhi/kicad-footprint-generator/pull/18
  - https://github.com/pointhi/kicad-footprint-generator/pull/14

Thanks!
JAN

**Pull request closed without merging**
