### PR TITLE
Preserve line ordering

### PR DESCRIPTION
**Pull request by diggit**
This PR follows PR #21 and closes issue #22.  Line order is preserved and formatting matches KiCad's output. This was problem of DRAW part of symbol.
*note: Kicad may reorder lines if they are ordered in different way than he likes it. But checklib.py does not touch their order anymore.*

**test**
Tested on atmel library. I tried --fix on some valid component and resulting file makes exactly same changes as resaving library in KiCad.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Patrik,

It seems to add an extra space in the process for text and pin entries, resulting in a bigger than normal diff. I tried it on the audio.lib and here is a sample of the modifications:

> -T 0 -100 -50 60 0 0 0 + Normal 0 C C
> -T 0 -100 350 60 0 0 0 + Normal 0 C C
> -T 0 100 250 60 0 0 0 + Normal 0 C C
> -P 2 0 1 0 -25 200 -25 -200 N
> -P 2 0 1 0 25 -200 25 200 N
> -P 10 0 1 0 -150 350 -150 -350 -100 -400 100 -400 150 -350 150 350 100 400 -100 400 -150 350 -150 350 f
> +T 0 -100 -50 60 0 0 0 +  Normal 0 C C
> +T 0 -100 350 60 0 0 0 +  Normal 0 C C
> +T 0 100 250 60 0 0 0 +  Normal 0 C C
> +P 2 0 1 0  -25 200  -25 -200 N
> +P 2 0 1 0  25 -200  25 200 N
> +P 10 0 1 0  -150 350  -150 -350  -100 -400  100 -400  150 -350  150 350  100 400  -100 400  -150 350  -150 350 f

**Comment by diggit** [comment]
I can't spot differences in your diff output.
I did not touch pin (X) handling, only Text (T) and polyline (P).

Did you resave library in kicad at first? These changes were made to follow KiCad's formatting.

**Comment by CarlPoirier** [comment]
You are right, the extra spaces are also generated by KiCad. I was differentiating at first with an unsaved library.

Still, I suggest the script doesn't add that extra space and reduces the library diff. KiCad should be fixed instead .

**Comment by diggit** [comment]
Ok, I only tried to match KiCad format.
Can you create bugreport on this? You'll probably get more attention than me.
[Polyline whitespace problem line](https://github.com/KiCad/kicad-source-mirror/blob/master/eeschema/lib_polyline.cpp#L66)
[Text whitespace problem line](https://github.com/KiCad/kicad-source-mirror/blob/master/eeschema/lib_text.cpp#L77)
They just need to remove 1 leading space on these lines.

**Comment by CarlPoirier** [comment]
It's great now! Thanks a bunch for your contribution. I'll take care of the KiCad side of the equation.

**Comment by CarlPoirier** [comment]
KiCad now does not write the extra spaces. It's been committed in bzr revision 6331.

**Pull request merged**
