### PR TITLE
Fixed file save fail

### PR DESCRIPTION
**Pull request by 4x5dm**
Fixed file save fail shown in issue #96 .

### CODE REVIEW

**Comment by poeschlr** [comment]
The open function of python 3 is not compatible to the one used in python 2.x
The solution is to use io.open (This function has the same signature as open in python 3)

See:
http://stackoverflow.com/questions/40491158/newline-does-not-work-with-python-2-7

https://docs.python.org/3/howto/pyporting.html#text-versus-binary-data

**Comment by SchrodingersGat** [comment]
Hi @4x5dm thanks for raising this, but the brand new KLC scripts (see https://github.com/KiCad/kicad-library-utils/pull/81) are about to be merged and they do not use this keyword, so the problem should be fixed).

**Comment by SchrodingersGat** [comment]
@4x5dm can you confirm if the problem still exists in the new scripts?

**Comment by 4x5dm** [comment]
All works. Thanks!

**Pull request closed without merging**
