### PR TITLE
Add script to check 3D model coverage

### PR DESCRIPTION
**Pull request by hackscribble**
I offer for consideration this script `check_3d_coverage.py` as a candidate to be added to the utilities.  It is intended as a data cleanup / planning tool to help decide where work is required to improve the 3D model collection.  It does **not** replace the detailed validation of the Rule 10.4 check script.

The script builds a list of 3D models referenced in the footprint modules in either (a) all `.pretty` folders on disk, or (b) a specified folder.  It highlights modules without a valid reference to a `.wrl`, `.step` or `.stp` model.

The script then looks for the 3D models in the associated `.3dshapes` folder in the library on disk.  It highlights missing models, and also any `.wrl` models that are not referenced by any footprints.

**EDIT** I have added a command line argument to switch the checking between `kicad-library/modules/packages3d` and the `packages3D` repo.

Sample output ...

```
Checking Potentiometers (contains 128 modules)
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_Trimmer-EVM3E.kicad_mod
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_Trimmer-EVM3S_R.kicad_mod
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_Trimmer_VishaySpectrol_Econtrim-Type36M.kicad_mod
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_Trimmer_VishaySpectrol_Econtrim-Type36P.kicad_mod
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_Trimmer_VishaySpectrol_Econtrim-Type36T.kicad_mod
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_Trimmer_VishaySpectrol_Econtrim-Type36X.kicad_mod
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_Trimmer_VishaySpectrol_Econtrim-Type36k.kicad_mod
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_WirePads.kicad_mod
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_WirePads_Small.kicad_mod
- No model file specified in /home/ray/KiCad Contributing/Potentiometers.pretty/Potentiometer_WirePads_largePads.kicad_mod
- No 3D model for reference Potentiometer_Alps_RK097_Double_Vertical.wrl in module Potentiometer_Alps_RK097_Double_Vertical.kicad_mod
- No 3D model for reference Potentiometer_Alps_RK09K_Horizontal.wrl in module Potentiometer_Alps_RK09K_Horizontal.kicad_mod
- No 3D model for reference Potentiometer_Alps_RK09L_Double_Horizontal.wrl in module Potentiometer_Alps_RK09L_Double_Horizontal.kicad_mod
- No 3D model for reference Potentiometer_Alps_RK09L_Double_Vertical.wrl in module Potentiometer_Alps_RK09L_Double_Vertical.kicad_mod
- No 3D model for reference Potentiometer_Alps_RK09L_Sleve_Single_Horizontal.wrl in module Potentiometer_Alps_RK09L_Sleve_Single_Horizontal.kicad_mod
- No 3D model for reference Potentiometer_Bourns_PRS11S_Horizontal.wrl in module Potentiometer_Bourns_PRS11S_Horizontal.kicad_mod
<snip>
- No 3D model for reference Potentiometer_VishaySpectrol_148_149_Single_Horizontal_MountLS.wrl in module Potentiometer_VishaySpectrol_148_149_Single_Horizontal_MountLS.kicad_mod
- No 3D model for reference Potentiometer_VishaySpectrol_248GJ_249GJ_Horizontal.wrl in module Potentiometer_VishaySpectrol_248GJ_249GJ_Horizontal.kicad_mod
- No 3D model for reference Potentiometer_VishaySpectrol_248GJ_249GJ_Horizontal_MountLS.wrl in module Potentiometer_VishaySpectrol_248GJ_249GJ_Horizontal_MountLS.kicad_mod
- 61 module warnings
```
```
Checking Housings_DFN_QFN (contains 84 modules)
- No 3D model for reference DFN-12-1EP_3x3mm_Pitch0.5mm.wrl in module DFN-12-1EP_3x3mm_Pitch0.5mm.kicad_mod
- 1 module warnings
- Unused .wrl model QFN-24_4x4mm_Pitch0.5mm.wrl
- 1 unused model warnings
```

Command line arguments ...

```
usage: check_3d_coverage.py [-h] [-p PRETTY] [-r ROOT] [--usepackages3D] [-v]
                            [--nocolour]

Checks which KiCad footprint files (.kicad_mod) reference 3D model files that
exist in the KiCad library.

optional arguments:
  -h, --help            show this help message and exit
  -p PRETTY, --pretty PRETTY
                        name of footprint library to check (e.g.
                        Housings_SOIC) (default is all libraries)
  -r ROOT, --root ROOT  path to root KiCad folder (defalt is ../../)
  --usepackages3D       check against the packages3D repo instead of kicad-
                        library
  -v, --verbose         enable verbose output
  --nocolour            do not use colour text in output
```

### CODE REVIEW

**Comment by Shackmeister** [comment]
I would be great if this could be a part of the "status of the libraries" to give an overall impression. Nice work!

**Comment by SchrodingersGat** [comment]
Hi @hackscribble why did you close this? Sorry I have not had a chance to review this yet. Is it still functional?

**Comment by hackscribble** [comment]
Yes, still functions.  I was a bit too keen when doing some housekeeping :smile:

**Comment by hackscribble** [comment]
Updated to provide more detail on unused models.  As used here ... https://github.com/KiCad/kicad-library/issues/1411#issuecomment-317353828

**Comment by SchrodingersGat** [comment]
Thanks @hackscribble :)

**Pull request merged**
