### PR TITLE
Bugfixes for Rule 6.6 (CourtYard)

### PR DESCRIPTION
**Pull request by jkriege2**
- better claculation of actual courtyard clearance 
- now uses offsets in the pad center

### CODE REVIEW

**Comment by jkriege2** [comment]
@SchrodingersGat if you have time: This should reduce the noise by courtyard-checks a bit!

**Comment by SchrodingersGat** [comment]
I am close to having the new KLC ready to go - check updates here - https://github.com/KiCad/kicad-library-utils/pull/81

Can we hold off on this PR until the new KLC is in? At this stage it's going to just create merge errors for the new KLC

**Comment by jkriege2** [comment]
hmmm ... we can, but then the rule won't work correctly in some cases and give even more strange outputs ... but you can merge your's first and the I try to merge mine in?

**Comment by CarlPoirier** [comment]
Hi @jkriege2 @SchrodingersGat,

Is this PR still relevant? If so, I can review it once the conflicts are resolved.

**Comment by SchrodingersGat** [comment]
I believe that @jkriege2 was going to look into this once more now that KLC 2.0 is out.

**Comment by jkriege2** [comment]
I think we can close this for now ... and I will work on an updated soluation, based on the current status of the scripts ;-)

**Pull request closed without merging**
