### PR TITLE
Fixes for KLC 1.04

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Strip out carriage return characters in addition to newlines

### CODE REVIEW

**Comment by jkriege2** [comment]
Could you repost this, as I erroneously merged and reverted this ....

Thanks and sorry for the inconvensience,
JAN

**Comment by jkriege2** [comment]
@SchrodingersGat The problem seems to be the line `print("Description missing for '{name}'".format(name=name))` in ` schlib/schlib.py`, which generates a lot of unnecessary outputs ...

**Comment by SchrodingersGat** [comment]
Ah yep that was a debugging line that I seem to have left in by mistake.

**Comment by SchrodingersGat** [comment]
I have cherry-picked the two lines and pushed them to master

**Comment by jkriege2** [comment]
OK!
Thanks,
JAN

**Pull request merged**
