### PR TITLE
allow roundrect pads, which will be available in KiCAD v5

### PR DESCRIPTION
**Pull request by jkriege2**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I'm happy with this but we should not merge until we mark the v4 libs as archived, as those libs are currently served by these scripts also.

**Comment by pointhi** [comment]
in v5 we get polygone pads as well

**Comment by jkriege2** [comment]
Hi!

I added "custom" to the allowed pad shpaes ... now all available pad shapes are allowed, so should we maybe remove that rule altogether?

JAN

**Comment by SchrodingersGat** [comment]
Yep, let's remove it, especially given it is a "hidden" (undocumented) rule.

**Comment by jkriege2** [comment]
is removed ... can be merged?

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
