### PR TITLE
Update comparelibs.py to better work with Jenkins

### PR DESCRIPTION
**Pull request by reportingsjr**
I had to change how the file parsing was done as well as add a nocolor flag along with some other adjustments. This script is running on my fork of the kicad library if you want to see the results: https://github.com/reportingsjr/kicad-library/pull/8

The worst thing about this script right now is that if a new library gets added and someone doesn't have it when they do a PR the script will barf. Maybe something to fix once this is up and running.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Jon,

You have commented the "# Display any deleted components" section and when I try to test it, the deleted component isn't listed.

Carl

**Comment by reportingsjr** [comment]
Yes, I didn't consider this useful for the comments on failed pull requests. If you want it to display the number of deleted components in that comment I can definitely add it back in.

**Comment by SchrodingersGat** [comment]
If you look at https://github.com/KiCad/kicad-library-utils/pull/50 I have addressed this extra output by disabling it unless you pass the "--verbose" flag

**Comment by reportingsjr** [comment]
Ah, ok! That looks good!

Will you merge that? I'll update this PR with those changes and hopefully we should be good to merge this in then.

**Comment by CarlPoirier** [comment]
Knowing that symbols have been deleted at first glance is definitely useful, isn't it? Will Jenkins use the --verbose option?

**Comment by reportingsjr** [comment]
I suppose it isn't a bad idea to include that. I'll tell it to use the verbose option once that PR is merged in.

**Comment by SchrodingersGat** [comment]
Carl if you want to have a look at https://github.com/KiCad/kicad-library-utils/pull/50 when you have time :)

**Comment by CarlPoirier** [comment]
Nevermind, I thought deleted symbols wouldn't appear at all if the --verbose wasn't listed. #50 is merged, so if you can fix the conflicts this one can be merged as well. Oliver you can approve the pulls as well, as usual.

**Comment by SchrodingersGat** [comment]
@reportingsjr now there's a conflict - fix this and we can proceed :)

**Comment by reportingsjr** [comment]
Alright! This is ready to be pulled in!

**Comment by CarlPoirier** [comment]
It's great, thanks!

**Comment by reportingsjr** [comment]
And now that we have all of this working.. I don't know if the script is going to be working for a while >.<.

The jenkins github plugin has a bug in it. Looking in to it now, but don't expect anything for a while. Sorry :(

**Comment by CarlPoirier** [comment]
Is it known?

**Comment by reportingsjr** [comment]
Yes, I've provided a little bit of info here: https://github.com/jenkinsci/ghprb-plugin/issues/260

I don't know how quickly it will get fixed. If there isn't any progress in the next few days I'm going to try and revert the plugin to the old version I was using.

**Pull request merged**
