### PR TITLE
Added script to check for footprint errors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Similar to the [3D model script](https://github.com/KiCad/kicad-library-utils/pull/117) submitted by @hackscribble this script checks a directory of .lib files to see where there may be footprint violations

- Checks empty footprint fields
- Checks for invalid footprint formatting
- Checks for footprints that do not exist

A good way to quickly show where effort needs to be directed to fix footprint associations.

### CODE REVIEW

**Comment by hackscribble** [comment]
Looks good :smile: 

Would it be useful to add a list of the footprint filters (if any), especially for symbols with an empty footprint field?

**Comment by jkriege2** [comment]
Hi!

nice script ... I think to make it even more useful, could you change these things:
1. an example in the `--help`-message would be great, I don't really understand, what I can specify ... e.g. can I also specify a single .lib, or only a directory of libs? Ca I specify a directory of .pretty's or only a single .pretty? ...
2. also: Can wildcards be used?
3. The output is a bit unformatted ... the general error messages, which precede the detailed lists should be highlghted more (e.g. using `=================================================` and/or larger spaces in between ...)
4. Could we also check whether FPFilters are given and whether any of the FPFilters matches the given footprint (if available)? ... maybe this functionality could also be part of the normal lib-check-scripts ?

Best,
JAN

**Comment by SchrodingersGat** [comment]
Note to self : Add facility to search for all symbols that reference a particular footprint

**Comment by poeschlr** [comment]
@SchrodingersGat i think this has been forgotten and now it needs a merge.

**Comment by poeschlr** [comment]
@jkriege2 is this functionality already in our scripts?

**Comment by Ratfink** [comment]
`checklib.py` performs these checks as part of S5.1, if the path to the footprints is given (otherwise, it still checks that the format is right and warns if it thinks there should be a default footprint set).  Closing this as it would be redundant.

**Pull request closed without merging**
